import glob
import os
import re
import sys
import empty_dict

# Directory containing backbone PDB files generated by CA_C_N_parsing.py
input_dir = './Backbone'
# Directory where label files will be written
output_dir = './Labels'
os.makedirs(output_dir, exist_ok=True)

labels_dict = {}
B_strand_dict = {}
C_strand_dict = {}
E_strand_dict = {}
F_strand_dict = {}

# Compile a regex to extract pdb_id, chain, start, end, seg from filenames like:
pattern = re.compile(
    r'^Backbone_'
    r'(?P<pdb_id>[^_]+)_'
    r'(?P<chain>[^_]+)_'
    #r'(?P<start>-?\d+)_to_'
    r'(?P<start>-?\d+)_'
    r'(?P<end>\d+(?:[A-Za-z]+)?)_'
    r'seg(?P<seg>\d+)\.pdb$'
)

def Label(file_path):
    labels = []
    B_strand, C_strand, E_strand, F_strand = [], [], [], []
    i = 0
    with open(file_path, 'r') as file:
        for line in file:
            atom = line[12:16].strip()
            if atom in ("CA", "C", "N"):
                code = line[21].strip()
                if code == 'B':
                    labels.append(1)
                    B_strand.append(i)
                elif code == 'E':
                    labels.append(1)
                    E_strand.append(i)
                elif code == 'C':
                    labels.append(-1)
                    C_strand.append(i)
                elif code == 'F':
                    labels.append(-1)
                    F_strand.append(i)
                else:
                    labels.append(0)
                i += 1
    return labels, B_strand, C_strand, E_strand, F_strand

for pdb_file in glob.glob(os.path.join(input_dir, '*.pdb')):
    fname = os.path.basename(pdb_file)
    m = pattern.match(fname)
    if not m:
#        print(f"Skipping (unrecognized pattern): {fname}")
        continue

    pdb_id = m.group('pdb_id')
    chain  = m.group('chain')
    start  = int(m.group('start'))
    end    = (m.group('end'))
    seg    = int(m.group('seg'))

    # Generate labels
    labels, B_strand, C_strand, E_strand, F_strand = Label(pdb_file)
    key = re.sub(r'^Backbone_', '', fname)
    key = os.path.splitext(key)[0]
    
    labels_dict[key] = labels
    B_strand_dict[key] = B_strand
    C_strand_dict[key] = C_strand
    E_strand_dict[key] = E_strand
    F_strand_dict[key] = F_strand

    # Construct label file name similar to the PDB naming
    label_fname = f"Labels_{pdb_id}_{chain}_{start}_{end}_seg{seg}.txt"
    out_path = os.path.join(output_dir, label_fname)

    # Write labels, one per line
    with open(out_path, 'w') as wf:
        for lbl in labels:
            wf.write(f"{lbl}\n")

labels_dict = empty_dict.prune_dict(labels_dict)
B_strand_dict = empty_dict.prune_dict(B_strand_dict)
C_strand_dict = empty_dict.prune_dict(C_strand_dict)
E_strand_dict = empty_dict.prune_dict(E_strand_dict)
F_strand_dict = empty_dict.prune_dict(F_strand_dict)
#print(B_strand_dict['1B88_A_3_to_114'])
def get_Labels(key):
    return labels_dict[key]

##   print(f"Wrote labels to {out_path}")
#print(len(labels_dict))
#print(len(B_strand_dict))
#print(len(C_strand_dict))
#print(len(E_strand_dict))
#print(len(F_strand_dict))
